### PR TITLE
Fix DoctrineQueryObjectDataSource count behavior

### PR DESCRIPTION
**Pull request by mrtnzlml**
This is the only difference between `count` and `getTotalCount`. And I think that this control should take care of current `count` of selected items instead of total count of whole set. With this modification you can use this nogrid with filtered QO and paginator. Does it make sense?

### CODE REVIEW

**Comment by davidkudera** [comment]
Sorry, I forgot this PR... Shame on me..

That method is here only for one purpose - paginator. I have to set total count of all items here: https://github.com/Carrooi/Nette-NoGrid/blob/master/src/NoGrid.php#L203

**Comment by mrtnzlml** [comment]
Of course, but you probably want to set count of currently filtered result set. Not whole set every time. But it was long time ago so I am not sure if I remember correctly.

**Comment by davidkudera** [comment]
Yeah, but that would break the paginator, because it needs to know the total count of all items, so it can count number of pages. Developers can use these methods: `$grid->getCount()` or for total items count `$grid->getTotalCount()`.

I'll close that PR for now if you don't mind. :wink: Please reopen if you'll need

**Comment by mrtnzlml** [comment]
Ok, never mind. It was maybe only my bad use case. I am sure it didn't make any sense. If I remember correctly, I had this grid inside of another component like this:

``` php
protected function createComponentGrid()
{
    $query = (new PagesQueryAdmin())
        ->withCategories($this->category_id) // <- simple filter by selected category
        ->withTags($this->tag_id) // <- simple filter by selected tag
        ->withAuthors($this->author_id); // <- and simple filter by selected author
    $dataSource = new DoctrineQueryObjectDataSource($this->em->getRepository(Page::class), $query);
    $grid = $this->gridFactory->create($dataSource);
    return $grid;
}
```

The point is, that the count of all items doesn't make sense, because I really don't care about all pages, I care only about filtered pages and that's not the same thing. And again - if I remember correctly - the grid was trying to create paginator for non-filtered resultset.

Well at this point it sounds quite weird to me. Haha there was probably error in my `doCreateCountQuery` implementation. I'm sorry...

**Pull request closed without merging**
